export interface IUserPermissions {
    admin_dashboard: boolean
    list_client: boolean
    add_client: boolean
    edit_client: boolean
    export_client_data: boolean
    list_process: boolean
    add_process: boolean
    process_start_stop: boolean
    cron_start_stop: boolean
    export_process_Data: boolean
    bulk_message_listing: boolean
    upload_bulk_message: boolean
    view_bulkMessage: boolean
    list_customer: boolean
    upload_data_file: boolean
    upload_reAssign_file: boolean
    export_customer_data: boolean
    list_deActivate_customer: boolean
    upload_deActivate_customer_file: boolean
    export_deActivate_customer_data: boolean
    list_disposition: boolean
    export_disposition: boolean
    agent_process_map_listing: boolean
    agent_process_map_export: boolean
    payment_listing: boolean
    upload_payment: boolean
    payment_export: boolean
    list_template: boolean
    list_call_summary: boolean
    call_summary_data_export: boolean
    list_agent_activity: boolean
    agent_activity_data_export: boolean
    list_merchant: boolean
    add_merchant: boolean
    upload_merchant_data: boolean
    merchant_edit: boolean
    delete_merchant: boolean
    export_merchant_data: boolean
    list_logs: boolean
    logs_export: boolean
    logs_view: boolean
    communication_stats: boolean
    agent_process_map_data: boolean
    list_permission: boolean
    employee_directory: boolean
    add_employee: boolean
    edit_employee: boolean
    delete_employee: boolean
    export_employee: boolean
    isg_flag: boolean
    edit_process: boolean
    merchant_status: boolean
    roles_management_listing: boolean
    add_role: boolean
    edit_role: boolean
    delete_role: boolean
    list_org_chart: boolean
    list_settlement: boolean
    list_client_analysis: boolean
    export_client_analysis: boolean
    client_chart_analysis: boolean
    client_tabular_analysis: boolean
    list_new_process: boolean
    list_edit_new_process: boolean
    collection_customer_notice_view: boolean
    reports: boolean
    export_reports: boolean
}