#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Running Lint-Staged
yarn lint-staged ||
(
    echo '🤢🤮🤢🤮 Your code looks disgusting, Format or Styling is not up-to the standards. 🤢🤮🤢🤮
            Lint Staged check failed. Run npm run format & npm run lint, add changes and try commit again.';
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'