name: Publish to npm

on:
  release:
    types: 
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version
          registry-url: 'https://registry.npmjs.org/'  # npm registry URL
      
      - name: Install npm dependencies
        run: npm install --legacy-peer-deps
      
      - name: Build packages
        run: npm run build  # Make sure your build script handles all packages if necessary

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Use GitHub Secrets for your npm token
        run: |
          # Publish each package sequentially
          for package in packages/core packages/redis packages/rmq packages/database packages/aws; do
            echo "Publishing $package..."
            cd $package
            npm publish --access public
            cd -  # Go back to the root directory
          done
