name: Publish npm package

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Set Node.js version to 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test

      - name: Publish to npm
        run: npm publish --access public   # Ensure it's published as public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}   # Store your npm token as a secret in GitHub
