name: Publish to npm

on:
  release:
    types: 
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify your Node.js version
          registry-url: 'https://registry.npmjs.org/'  # npm registry URL
      
      - name: install npm 
        run: npm install --legacy-peer-deps
      
      - name: npm build 
        run: npm run build

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Use GitHub Secrets for your npm token
        run: npm publish --access public
